### ISSUE TITLE
Correct License and Copyright

### ISSUE THREAD

**Issue by jobara** [fluid-project/uio-plus#1]
## Describe the bug

The [LICENSE.txt](https://github.com/fluid-project/uio-plus/blob/master/LICENSE.txt#L5-L7) file and the [package.json](https://github.com/fluid-project/uio-plus/blob/master/package.json#L5) file are out of sync when mentioning the License. Also the [copyright statement in the LICENSE.txt](https://github.com/fluid-project/uio-plus/blob/master/LICENSE.txt#L1) needs to be updated with the centralized copyright. 

### Expected

The License should be BSD-3  and the copyright should use the centralized version.

**Comment by msaaddev** [comment]
@jobara to get a clear understanding about this issue, you want the license of UIO+ to change to BSD-3 and the centralized version means default BSD-3 template?

**Comment by jobara** [comment]
@

> @jobara to get a clear understanding about this issue, you want the license of UIO+ to change to BSD-3 and the centralized version means default BSD-3 template?

@msaaddev thanks for your interest. I'm actually in the middle of addressing this issue. And just for reference the centralized copyright is regarding the use of the AUTHORS.md file and the copyright statements in the JS files.

**Comment by msaaddev** [comment]
@jobara thank you for clearing that.
