### ISSUE TITLE
Update CI to run against latest LTS versions of Node

### ISSUE THREAD

**Issue by jobara** [fluid-project/uio-plus#26]
## Describe the bug

Currently CI runs agains Node 10. Node 12 and 14 will be the latest LTS versions by the end of this month.

https://nodejs.org/en/about/releases/

![Node Release Schedule](https://user-images.githubusercontent.com/556024/96925828-bd599200-1482-11eb-8de4-36b63cf97792.png)

### Expected behavior
CI should run against Node v12 and v14 to track latest LTS releases.

**Comment by cindyli** [comment]
Merged at https://github.com/fluid-project/uio-plus/commit/89f66180d378f59cac9670da0824a0018a62fefd
